# A2 OWO FARMER - Combined OwO Bot Suite
# Made by Ayush Rajdev & Anzar Iqbal

import discord
from discord.ext import commands
import colorama
from colorama import Fore
import asyncio
import os

colorama.init()

PREFIX = "."
dmcs = False

class AutoFarm(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        global PREFIX
        PREFIX = bot.prefix if hasattr(bot, 'prefix') and bot.prefix else "."

    async def cog_load(self):
        self.bot.log("SYS", "AutoFarm cog loaded")

    @commands.command()
    async def help(self, ctx):
        await ctx.reply(
            "> **Auto OwO Ban Bypass**\n"
            "> **" + PREFIX + "AutoOwO - -** ```Auto OwO With BanBypass```\n"
            "> " + PREFIX + "**StopAutoOwO - -** ```Stops The Bot```"
        )

    @commands.command()
    async def stopautoOwO(self, ctx):
        global dmcs
        dmcs = False
        await ctx.reply("> **Shut Down || Log Out Successfully**")
        self.bot.log("SYS", "AutoFarm stopped by user")
        await self.bot.close()

    @commands.command(pass_context=True)
    async def AutoOwO(self, ctx):
        await ctx.message.delete()
        await ctx.send(
            "> **Auto OwO Ban Bypass Enabled**\n"
            "> **Made By : AyushRajdev**"
        )
        global dmcs
        dmcs = True
        while dmcs:
            async with ctx.typing():
                await ctx.send('owoh')
                self.bot.log("CMD", "AutoFarm: owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                self.bot.log("CMD", "AutoFarm: sell all")
                await ctx.send('owo flip 100')
                self.bot.log("CMD", "AutoFarm: flip 100")
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                self.bot.log("CMD", "AutoFarm: cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(11)
                await ctx.send('owoh')
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                await asyncio.sleep(12)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(5)
                await ctx.send('owoh')
                await asyncio.sleep(17)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(12)
                await ctx.send('owo cash')
                await asyncio.sleep(15)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(14)
                await ctx.send('owo cash')
                await asyncio.sleep(300)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                await asyncio.sleep(14)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(11)
                await ctx.send('owoh')
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                await asyncio.sleep(12)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                await asyncio.sleep(4)
                await ctx.send('owoh')
                await asyncio.sleep(12)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(16)
                await ctx.send('owo cash')
                await asyncio.sleep(14)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(4)
                await ctx.send('owo cash')
                await asyncio.sleep(11)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(11)
                await ctx.send('owo cash')
                await asyncio.sleep(900)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(11)
                await ctx.send('owoh')
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                await asyncio.sleep(12)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                await asyncio.sleep(5)
                await ctx.send('owoh')
                await asyncio.sleep(17)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(12)
                await ctx.send('owo cash')
                await asyncio.sleep(15)
                await ctx.send('owoh')
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                await asyncio.sleep(13)
                await ctx.send('owoh')
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                await ctx.send('owo flip 100')
                await asyncio.sleep(14)
                await ctx.send('owo cash')
                await asyncio.sleep(1200)

async def setup(bot):
    cog = AutoFarm(bot)
    await bot.add_cog(cog)


def run_standalone(token):
    print(f"{Fore.GREEN}A2 OWO FARMER - Auto Farm Standalone{Fore.RESET}")
    print(f"{Fore.GREEN}Made by Ayush Rajdev & Anzar Iqbal{Fore.RESET}")
    print()
    bot = commands.Bot(command_prefix=PREFIX, help_command=None, case_insensitive=True, self_bot=True)

    @bot.event
    async def on_ready():
        activity = discord.Activity(type=discord.ActivityType.playing, name="A2 OWO FARMER")
        await bot.change_presence(status=discord.Status.idle, activity=activity)
        print(f"Auto Farm Connected as: {bot.user.name}")

    @bot.command()
    async def help(ctx):
        await ctx.reply(f"> **Auto OwO Ban Bypass**\n> **{PREFIX}AutoOwO - -** Auto OwO With BanBypass\n> {PREFIX}**StopAutoOwO - -** Stops The Bot")

    @bot.command()
    async def stopautoOwO(ctx):
        await ctx.reply("> **Shut Down || Log Out Successfully**")
        await bot.close()

    @bot.command(pass_context=True)
    async def AutoOwO(ctx):
        await ctx.message.delete()
        await ctx.send("> **Auto OwO Ban Bypass Enabled**\n> **Made By : AyushRajdev**")
        global dmcs
        dmcs = True
        while dmcs:
            async with ctx.typing():
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(11)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(12)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(5)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(17)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(12)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(15)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(14)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(300)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(14)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(11)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(12)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(4)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(12)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(16)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(14)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(4)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(11)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(11)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(900)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(8)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await asyncio.sleep(5)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(11)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(18)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(12)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(10)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(5)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(17)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(12)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(15)
                await ctx.send('owoh')
                print("succefully owoh")
                await asyncio.sleep(15)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("succefully owo flip 100")
                await asyncio.sleep(9)
                await ctx.send('owo cash')
                print("succefully cash")
                await asyncio.sleep(13)
                await ctx.send('owoh')
                print("hunting using owoh")
                await asyncio.sleep(14)
                await ctx.send('owo sell all')
                print("succefully sell")
                await ctx.send('owo flip 100')
                print("flipped 100 owocny")
                await asyncio.sleep(14)
                await ctx.send('owo cash')
                print("balance cmd ran")
                await asyncio.sleep(1200)

    bot.run(token)


if __name__ == "__main__":
    token = input("Enter token: ").strip()
    run_standalone(token)
